"""make hashed_password nullable

Revision ID: 9e6bf53036ad
Revises: d48ec2af0e15
Create Date: 2026-03-10 16:33:03.165412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e6bf53036ad'
down_revision: Union[str, None] = 'd48ec2af0e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
